server:
  port: 8080
  servlet:
    contextPath:

spring:
  jackson:
    time-zone: Asia/Seoul
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 2
      maximum-pool-size: 4

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 1s
      password: ${REDIS_PASSWORD}

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      model: gpt-4o

oauth2:
  client:
    registration:
      kakao:
        client_id: ${KAKAO_CLIENT_ID} # REST API
      apple:
        client-id: ${APPLE_CLIENT_ID}
        team-id: ${APPLE_TEAM_ID}
        key-id: ${APPLE_KEY_ID}
        audience: https://appleid.apple.com
        grant-type: authorization_code

jwt:
  secret: ${JWT_SECRET}
  access-token-expire-time-in-hours: ${JWT_ACCESS_TOKEN_TIME}
  refresh-token-expire-time-in-hours: ${JWT_REFRESH_TOKEN_TIME}

naver:
  client:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}

odsay:
  base-url: https://api.odsay.com/v1/api/searchPubTransPathT
  api-key: ${ODSAY_CLIENT_API_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health

logging:
  level:
    root: info

decorator:
  datasource:
    p6spy:
      enable-logging: false